# Generated by Django 2.2.4 on 2019-11-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmbucket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmbucket',
            name='email',
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='avset',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='disks',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='os_disk',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='os_disk_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='primary_ip',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='resource_group',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='subscriptions',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='tags',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='vm_size',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
