  
FROM python:3
ENV PYTHONUNBUFFERED 1
ENV  DJANGO_ENV ${DJANGO_ENV}
ENV  DJANGO_DEBUG True
ENV  DJANGO_SECRET_KEY "Djangokey"
ENV  DJANGO_PROJECT_ROOT /code/
ENV AZURE_TENANT_ID=${AZURE_TENANT_ID}
ENV AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
ENV AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
RUN mkdir -p /code /code/logs /code/azurebucket/logs/ /code/scripts/logs
WORKDIR /code
RUN apt update && apt install vim cron -y
RUN pip install virtualenv 
RUN virtualenv venv 
COPY . /code/
RUN /bin/bash -c "source venv/bin/activate && pip install -r requirements.txt"
RUN /bin/bash -c "source venv/bin/activate && python /code/manage.py migrate"
CMD [ "./scripts/startgunicorn.sh" ]
EXPOSE 80 443 8000