version: '3'
services:
  azurebucket-web:
    container_name: azurebucket-web
    image: azurebucket-web:v0.1.0
    build: .
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    environment:
      - DJANGO_ENV= DEV
      - AZURE_TENANT_ID=5d3e2773-e07f-4432-a630-1a0f68a28a05
      - AZURE_CLIENT_ID=03828b49-95e3-4856-975f-8e12a6a50a73
      - AZURE_CLIENT_SECRET=djd5hzSLRcaK0jTJjl1+xKPGQcRxUXiYDkuB0fq+ZjY=      
  azurebucket-cron:
    container_name: azurebucket-cron
    image: "azurebucket-cron:v0.1.0" # 從 Docker Hub registry 來的 image
    environment:
      - DJANGO_ENV=DEV
      - AZURE_TENANT_ID=5d3e2773-e07f-4432-a630-1a0f68a28a05
      - AZURE_CLIENT_ID=03828b49-95e3-4856-975f-8e12a6a50a73
      - AZURE_CLIENT_SECRET=djd5hzSLRcaK0jTJjl1+xKPGQcRxUXiYDkuB0fq+ZjY=    
      - DJANGO_API_SERVER=azurebucket-web
    links:
      - "azurebucket-web"