version: '3'
services:
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn  --workers 4 -b 0.0.0.0:8000 azurebucket.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"