# Generated by Django 2.2.6 on 2019-11-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmbucket', '0002_auto_20191103_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vmbucket',
            old_name='subscriptions',
            new_name='subscription',
        ),
    ]
