# Generated by Django 2.2.6 on 2019-11-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmbucket', '0003_auto_20191103_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmbucket',
            name='created_time',
        ),
        migrations.AddField(
            model_name='vmbucket',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
