# Generated by Django 2.2.6 on 2019-11-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmbucket', '0004_auto_20191106_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmbucket',
            name='secondary_ips',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vmbucket',
            name='primary_ip',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
